# Override configuration for wallpaper cache plugin
# Mirror the original dde-wallpaper-cache.service security settings
[Service]
User=deepin-daemon
Group=deepin-daemon

# systemd 自动创建 /var/cache/dde-wallpaper-cache 并赋权给 deepin-daemon
CacheDirectory=dde-wallpaper-cache

ProtectSystem=strict
InaccessiblePaths=-/etc/shadow
InaccessiblePaths=-/etc/NetworkManager/system-connections
InaccessiblePaths=-/etc/pam.d
InaccessiblePaths=-/usr/share/uadp/

PrivateMounts=yes
NoNewPrivileges=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
PrivateTmp=yes
PrivateDevices=yes
PrivateNetwork=yes
PrivateUsers=yes
RestrictNamespaces=yes
LockPersonality=yes
RestrictRealtime=yes
RemoveIPC=yes
MemoryDenyWriteExecute=yes
